//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiAppDemo.Pages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiAppDemo.Pages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   .NET MAUI App Demo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインできませんでした。社員番号とパスワードを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Comman_Login {
            get {
                return ResourceManager.GetString("Error_Comman_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の形式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Converter {
            get {
                return ResourceManager.GetString("Error_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}～{2}の間で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Range {
            get {
                return ResourceManager.GetString("Error_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_Command_Login {
            get {
                return ResourceManager.GetString("Login_Command_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社員番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_No {
            get {
                return ResourceManager.GetString("Login_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1234 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_No_Placeholder {
            get {
                return ResourceManager.GetString("Login_No_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ●●●● に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login_Password_Placeholder {
            get {
                return ResourceManager.GetString("Login_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Command_logout {
            get {
                return ResourceManager.GetString("Main_Command_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page_Login {
            get {
                return ResourceManager.GetString("Page_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page_Main {
            get {
                return ResourceManager.GetString("Page_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page_Sub1 {
            get {
                return ResourceManager.GetString("Page_Sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブ2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page_Sub2 {
            get {
                return ResourceManager.GetString("Page_Sub2", resourceCulture);
            }
        }
    }
}
